title: grassnose
email: hello@grassno.se
description: thinking about thinkin' things
author: grassnose
baseurl: '/'
url: 'https://github.com/ianhundere/grassnose_blog'

# Social Profiles
bandcamp_username: grassnose
# github_username:
# facebook_username:
# instagram_username:
# linkedin_username:

google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
